config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "webinars#index"

  get "/upcoming" => "webinars#upcoming"
  get "/stories" => "webinars#stories"

  get "/content/all" => "webinars#all"

  resources :webinars, path: :content



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :webinars


end

app/models/webinar.rb
class Webinar < ApplicationRecord

  belongs_to :user
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end



end

app/controllers/webinars_controller.rb
class WebinarsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :all, :edit]

  def index
    @webinar = Webinar.order(created_at: :desc).limit(6)
  end

  def show
    @webinar1 = Webinar.all
    @webinar2 = @webinar1.sample(3)

    @webinar = Webinar.friendly.find(params[:id])

    unless @webinar.embed = true
      render 'webinars/video'
    else
      render 'webinars/artikel'
    end
  end

  def new
    @webinar = Webinar.new
  end

  def create
    @thread = Webinar.new(resource_params)
    @thread.user = current_user
    @thread.save
  end

  def edit
    @webinar = Webinar.friendly.find(params[:id])
  end

  def update
    @webinar = Webinar.friendly.find(params[:id])
    @webinar.update(resource_params)
    redirect_to content_all_path
  end

  def destroy
    @webinar = Webinar.friendly.find(params[:id])
    @webinar.destroy
    redirect_to content_all_path
  end

  def all
    @webinar = Webinar.all
    @webinar = @webinar.order(created_at: :desc)
  end

  def upcoming

  end

  def stories

  end



  private

  def resource_params
    params.require(:webinar).permit(:title, :speaker, :about, :date, :image, :embed, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-3 text-center-xs space--xs">
  <div class="container">
    <div class="row">
      <div class="col-sm-6"> <img alt="Image" class="logo" src="https://cdn.belajar.work/img/logo-hitam.png">
        <ul class="list-inline list--hover">
          <li> <a href="#"><span class="type--fine-print">Get Started</span></a> </li>
          <li> <a href="#"><span class="type--fine-print">help@belajar.work</span></a> </li>
        </ul>
      </div>
      <div class="col-sm-6 text-right text-center-xs">
        <ul class="social-list list-inline list--hover">
          <li><a href="#"><i class="socicon socicon-google icon icon--xs"></i></a></li>
          <li><a href="#"><i class="socicon socicon-twitter icon icon--xs"></i></a></li>
          <li><a href="#"><i class="socicon socicon-facebook icon icon--xs"></i></a></li>
          <li><a href="#"><i class="socicon socicon-instagram icon icon--xs"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <p class="type--fine-print">Improve your skill workflow. </p>
      </div>
      <div class="col-sm-6 text-right text-center-xs"> <span class="type--fine-print">© <span class="update-year">2018</span> Belajar.Work</span> <a class="type--fine-print" href="#">Privacy Policy</a> <a class="type--fine-print" href="#">Legal</a> </div>
    </div>
  </div>
</footer>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning': 'false' %>

</body>

</html>

app/views/layouts/_navbar.html.erb
<div class="nav-container">
  <div class="via-1525576882084" via="via-1525576882084" vio="navibar-top">
    <div class="bar bar--sm visible-xs">
      <div class="container">
        <div class="row">
          <div class="col-3 col-md-2">
            <%= link_to root_path do %>
              <img class="logo logo-dark" alt="logo" src="https://cdn.belajar.work/img/logo-dark.png"> <img class="logo logo-light" alt="logo" src="https://cdn.belajar.work/img/logo-light.png">
            <% end %>
          </div>
          <div class="col-9 col-md-10 text-right">
            <a href="#-mobile" class="hamburger-toggle" data-toggle-class="#menu1;hidden-xs hidden-sm"> <i class="icon icon--sm stack-interface stack-menu"></i> </a>
          </div>
        </div>
      </div>
    </div>
    <nav id="menu1" class="bar bar-1 hidden-xs bar--absolute bar--transparent">
      <div class="container">
        <div class="row">
          <div class="col-lg-1 col-md-2 hidden-xs">
            <div class="bar__module">
              <%= link_to root_path do %>
                <img class="logo logo-dark" alt="logo" src="https://cdn.belajar.work/img/logo-dark.png"> <img class="logo logo-light" alt="logo" src="https://cdn.belajar.work/img/logo.png">
              <% end %>
            </div>
          </div>
          <div class="col-lg-11 col-md-12 text-right text-left-xs text-left-sm">
            <div class="bar__module">
              <ul class="menu-horizontal text-left">
                <li> <%= link_to root_path, target: "_self" do %>Home <% end %> </li>
                <% if user_signed_in? %><% if current_user.level == 1 %>
                <li class="dropdown"> <span class="dropdown__trigger">Admin <sup><span class="badge badge-pill badge-warning">Restricted</span></sup></span>
                  <div class="dropdown__container">
                    <div class="container">
                      <div class="row">
                        <div class="dropdown__content col-lg-2">
                          <ul class="menu-vertical">
                            <li> <%= link_to "Story", content_all_path, target: "_self" %> </li>
                            <li> <%= link_to "Speaker", upcoming_path, target: "_self" %> </li>
                            <li> <%= link_to "User", upcoming_path, target: "_self" %> </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <% end %><% end %>
                <li> <%= link_to "Upcoming", upcoming_path, target: "_self" %> </li>
                <li> <a href="belajar.work" target="_self">Stories</a> </li>
                <li> <a href="belajar.work" target="_self">Our mission</a> </li>
                <li> <a href="belajar.work" target="_self">f.a.q </a> </li>
              </ul>
            </div>
            <div class="bar__module">

              <% if user_signed_in? %>
                <a class="btn btn--sm type--uppercase" href=""> <span class="btn__text">Halo <%= current_user.name %>
                                </span> </a>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary type--uppercase btn--sm btn__text" %>
              <% else %>
                <a class="btn btn--sm type--uppercase" href="/users/sign_in"> <span class="btn__text">login
                                                  </span> </a>
                <a class="btn btn--sm btn--primary type--uppercase" href="/users/sign_up">
                  <span class="btn__text">register</span> </a>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <title>Belajar.Work</title>
  <meta name="description" content="Belajar.Work provide any topics using webinar and screencast media platform." />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


  <link href="https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,400i,500,600,700" rel="stylesheet">

</head>

<body data-smooth-scroll-offset="77">


    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

app/views/layouts/application.html.slim
= javascript_include_tag Ckeditor.cdn_url

app/views/webinars/_form.html.erb
<script src="https://cdn.ckeditor.com/4.9.2/full-all/ckeditor.js"></script>
<div class="main-container">
  <section class="cover unpad--bottom switchable text-center-xs bg--dark">
    <div class="container">
      <div class="row justify-content-between align-items-center">
        <div class="col-md-6 col-lg-5 ">
          <h1> Admin Dashboard</h1>
        </div>
      </div>
  </section>
  <section class="space--xxs">
    <div class="container">
      <div class="row justify-content-center">
        <!-- <div class="col-md-10 col-lg-8"> -->

        <div class="col-md-12">

          <article>
            <!--end article title-->
            <div class="article__body">
              <%= form_for @webinar do |f| %>
                <form class="row">
                  <div class="col-md-12">
                    <%= f.label :title %>
                    <%= f.text_field :title, placeholder: "Type Title Here" %>
                  </div>
                  <div class="col-md-12">
                    <%= f.label :speaker %>
                    <%= f.text_field :speaker, placeholder: "Type Speaker Here" %>
                  </div>
                  <div class="col-md-12">
                    <%= f.cktext_area :about  %>
                  </div>
                  <div class="col-md-12">
                    <%= f.label :date %>
                    <%= f.text_field :date, placeholder: "Select Date Webinar Here", type: 'date' %>
                  </div>
                  <div class="col-md-12">
                    <%= f.label :cover %>
                    <%= f.text_field :image, placeholder: "Link Gambar Promosi" %>
                  </div>
                  <div class="col-md-12">
                    <%= f.label :video %>
                    <%= f.text_field :embed, placeholder: "Videonya bisa dikosongin" %>
                  </div>
                  <div class="col-md-12">
                    <%= f.label :content %>
                    <%= f.cktext_area :content, placeholder: "Diisi materinya" %>
                  </div>
                  <div class="col-md-12">
                    <%= f.submit 'Buat Story!', class: "btn btn--primary" %>
                  </div>
                </form>
              <% end %>
            </div>
          </article>
          <!--end item-->
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->

  </section>
  <section class="space--xxs">
    <div class="container space--xxs">
      <div class="row space--xxs">
        <div class="col-md-12 space--xxs">
          <hr>
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
</div>

app/views/webinars/_iklan.html.erb
<section class="space--xxs bg--secondary">
  <div class="container">
    <div class="row text-block">
      <div class="col-md-12">
        <h3>More recent stories</h3>
      </div>
    </div>
    <!--end of row-->
    <div class="row">
      <% @webinar2.shuffle.each do |web| %>
        <div class="col-md-4">
          <article class="feature feature-1">
              <%= link_to webinar_path(web), class: "block"  do %>
                <%= image_tag web.image %>
              <% end %>
            <div class="feature__body boxed boxed--border">
              <span><%= web.created_at.strftime("%d %b %Y") %>,</span> <em> Speaker: <%= web.speaker.titleize %></em>
              <h5><%= web.title.titleize %></h5>
              <a href="#">
                <%= link_to "Read More", webinar_path(web) %>
              </a>
            </div>
          </article>

        </div>
      <% end %>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

app/views/webinars/all.html.erb
<div class="main-container">
  <section class="cover unpad--bottom switchable text-center-xs bg--dark">
    <div class="container">
      <div class="row justify-content-between align-items-center">
        <div class="col-md-6 col-lg-5 ">
          <h1> Admin Dashboard</h1>
      </div>
    </div>
  </section>
  <section class="space--xxs">
    <div class="container">
      <div class="row justify-content-center">
        <!-- <div class="col-md-10 col-lg-8"> -->
        <div class="col-md-12">
          <article>
           <!--end article title-->
            <div class="article__body">
              <div><%= link_to '+ Story', new_webinar_path, class: "btn btn-primary" %></div>
                <table class="border--round table--alternate-row">
                  <thead>
                  <tr>
                    <th>Create</th>
                    <th>Title</th>
                    <th>Speaker</th>
                    <th>Action</th>
                  </tr>
                  </thead>

                  <tbody>
                  <% @webinar.each do |all| %>
                  <tr>
                    <td><%= all.created_at.strftime("%d %b %Y") %></td>
                    <td><%= all.title %></td>
                    <td><%= all.speaker %></td>
                    <td><%= link_to 'Edit', edit_webinar_path(all) %> | <%= link_to "Hapus", webinar_path(all), method: :delete, data: {confirm: "Yakin nih?"} %></td>
                  </tr>
                  <% end %>
                  </tbody>

                </table>



            </div>
          </article>
          <!--end item-->
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
  <section class="space--xxs">
    <div class="container space--xxs">
      <div class="row space--xxs">
        <div class="col-md-12 space--xxs">
          <hr>
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
</div>

app/views/webinars/artikel.html.erb
<div class="main-container">
  <section class="cover unpad--bottom switchable text-center-xs bg--dark">
    <div class="container">
      <div class="row justify-content-between align-items-center">
        <div class="col-md-6 col-lg-5 ">
          <h1> <%= @webinar.title.titleize %></h1>
          <div class="lead"><%=raw @webinar.about %><br></div>
          <a class="btn btn--primary type--uppercase" href="#"> <span class="btn__text"><%= @webinar.speaker.titleize %> </span> </a>
          <span class="block type--fine-print">or <a href="index.html">view the screencast</a></span></div>
        <div class="col-md-6"><img alt="Image" src="https://cdn.belajar.work/img/landing-5.jpg"></div>
      </div>
    </div>
  </section>
  <section class="space--xxs">
    <div class="container">
      <div class="row justify-content-center">
        <!-- <div class="col-md-10 col-lg-8"> -->
        <div class="col-6 col-md-4">.


          <div class="card" style="width: 100%;">
            <div class="card-body">
              <h5 class="card-title">Support Speaker!</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="#" class="btn btn-primary">Vote</a>
            </div>
          </div>




        </div>
        <div class="col-12 col-md-8">

          <article>
           <!--end article title-->
            <div class="article__body">
              <%=raw @webinar.content %>
            </div>
          </article>
          <!--end item-->
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
  <section class="space--xxs">
    <div class="container space--xxs">
      <div class="row space--xxs">
        <div class="col-md-12 space--xxs">
          <hr>
        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
  <section class="space--xxs">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10 col-lg-8 space--xxs">
          <div id="disqus_thread" class="space--xxs"></div>
          <script>

              /**
               *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
               *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
              /*
              var disqus_config = function () {
              this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
              this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
              };
              */
              (function () { // DON'T EDIT BELOW THIS LINE
                  var d = document, s = d.createElement('script');
                  s.src = 'https://belajarwork.disqus.com/embed.js';
                  s.setAttribute('data-timestamp', +new Date());
                  (d.head || d.body).appendChild(s);
              })();
          </script>
          <noscript>Please enable JavaScript to view the
            <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

        </div>
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
 <%= render 'iklan'%>
</div>

app/views/webinars/edit.html.erb
<%= render 'form' %>

app/views/webinars/index.html.erb
           <div class="main-container">
            <section class="cover unpad--bottom switchable text-center-xs bg--dark">
                <div class="container">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-md-6 col-lg-5 mt--3">
                            <h1> If You've Got the <b>Time</b>, We've Got the <b>Webinar.</b></h1>
                            <p class="lead">Belajar.Work provide any topics using webinar and screencast media platform.<br></p>
                            <a class="btn btn--primary type--uppercase" href="#"> <span class="btn__text">join our events </span> </a> <span class="block type--fine-print">or <a href="index.html">view the screencast</a></span> </div>
                        <div class="col-md-6"> <img alt="Image" src="https://cdn.belajar.work/img/landing-5.jpg"> </div>
                    </div>
                </div>
            </section>
            <section class="video video-1 text-center space--xxs bg--secondary">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="modal-instance">
                                <div class="video-play-icon video-play-icon--sm modal-trigger box-shadow"></div>
                                <div class="modal-container">
                                    <div class="modal-content bg-dark" data-width="60%" data-height="60%"> <iframe data-src="https://www.youtube.com/embed/T6EC4MMj2Xw?autoplay=1" allowfullscreen="allowfullscreen"></iframe> </div>
                                </div>
                            </div>
                            <h2>Short story about Belajar.Work<br></h2>
                        </div>
                    </div>
                </div>
            </section>
            <section class="space--xxs">
                <div class="container">
                    <div class="row text-block">
                        <div class="col-md-12">
                            <h3>More recent webinars &amp; screencasts<br></h3>
                        </div>
                    </div>
                    <div class="row">

                      <%	 @webinar.each do |w| %>
                        <div class="col-md-4">
                            <article class="feature feature-1">
                              <%= link_to webinar_path(w), class: "block" do %>
                                <%= image_tag w.image %>
                              <% end %>
                                <div class="feature__body boxed boxed--border"> <span><%= w.created_at.strftime("%d %b %Y") %>,</span> <em> Speaker: <%= w.speaker.titleize %></em>
                                    <h5><%= w.title.titleize %></h5>
							                      <%= link_to "Read More", webinar_path(w) %>
                                </div>
                            </article>
                        </div>
                        <%	 end %>
                    </div>
                </div>
            </section>
            <section class="switchable space--xxs bg--secondary">
                <div class="container">
                    <div class="row justify-content-between">
                        <div class="col-lg-5 col-md-6">
                            <div class="mt--3">
                                <h1>You <b>better</b> get inside <b>Webinar.</b></h1>
                                <p class="lead">Just few minutes, <b>We respect </b>about your privacy.<br></p>
                                <hr class="short">
                                <form action="https://work.us18.list-manage.com/subscribe/post?u=6b9e871348e6f5fe00f43804e&amp;id=b021f94d90" method="post">
                                    <div class="row">
                                        <div class="col-12"> <input name="FNAME" placeholder="First Name" id="mce-FNAME" type="text"> </div>
                                        <div class="col-12"> <input name="EMAIL" placeholder="Email Address" type="email" id="mce-EMAIL" > </div>
                                        <div class="col-12"> <button type="submit" class="btn btn--primary" name="subscribe" id="mc-embedded-subscribe">Subscribe</button> </div>
                                        <div class="col-12"> <span class="type--fine-print">By fill in the form, you agree to the <a href="#">Terms of Service</a></span> </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                        <div class="col-md-6 col-lg-5"> <img alt="Image" class="border--round box-shadow-wide" src="https://cdn.belajar.work/img/photography-9.jpg"> </div>
                    </div>
                </div>
            </section>

app/views/webinars/new.html.erb
<%= render 'form' %>

app/views/webinars/upcoming.html.erb
hallo

app/views/webinars/video.html.erb
ini adalah halaman video